### ISSUE TITLE
Responsive design issue with hotkeys information in small devices.

### ISSUE THREAD

**Issue by ByMykel** [LegendEffects/emote.land#1]
This is what I see in my mobile:

![Picture example](https://user-images.githubusercontent.com/38622893/123510574-a3f58f00-d67c-11eb-9467-49c8919ca8be.jpg)

Does it make sense to show that information in small devices? I thought about using flex-column in small devices or just hide that part.

**Comment by LegendEffects** [comment]
Seems to be an issue rooted in the flex utility styling where it selects immediate children. Flex wrap was applied here but more thought needs to go into how the text could be changed to fit mobile devices:
- Left Click -> Short Press
- Right Click -> Long Press

I'm unsure how favourites could work here.

**Comment by ByMykel** [comment]
Maybe implement double click for favorites?

**Comment by LegendEffects** [comment]
That would work, as for the text some utility classes could be added (.d-flex, .d-none, .md:d-flex, .md:d-none) and then swap between two sets of helpers; let me know if you're submitting a PR for this or if I should work on it.

**Comment by ByMykel** [comment]
I will submit a PR later.

**Comment by LegendEffects** [comment]
Fixed in latest commits.
